# SPDX-FileCopyrightText: 2026 ARMSX2 Contributors
# SPDX-License-Identifier: GPL-3.0+
#
# Script mode: writes OUT, a header defining GS_CACHE_BUILD_ID, the hash of every file named in LIST
# (paths relative to ROOT, one per line). The GS shader and pipeline caches stamp their files with
# it, so any change to the GS code or the shader sources discards what a previous build cached,
# with no version number for anyone to forget to bump.

file(STRINGS "${LIST}" files)
set(text "")
foreach(rel IN LISTS files)
	if(EXISTS "${ROOT}/${rel}")
		file(SHA256 "${ROOT}/${rel}" h)
	else()
		set(h "missing")
	endif()
	string(APPEND text "${rel} ${h}\n")
endforeach()
string(SHA256 id "${text}")
string(SUBSTRING "${id}" 0 32 id)

set(content "// Generated by cmake/GSCacheBuildId.cmake. Do not edit.\n#pragma once\n#define GS_CACHE_BUILD_ID \"${id}\"\n")
if(EXISTS "${OUT}")
	file(READ "${OUT}" old)
else()
	set(old "")
endif()
if(NOT old STREQUAL content)
	file(WRITE "${OUT}" "${content}")
else()
	# Unchanged: touch it so the build tool sees the output as newer than its inputs.
	file(TOUCH "${OUT}")
endif()
